import { Link } from "react-router-dom";

const sections = [
  {
    title: "Acceptance of Terms",
    content: [
      {
        text: "By using Resumetra, you agree to these Terms of Service. If you do not agree, do not use the service.",
      },
    ],
  },
  {
    title: "Description of Service",
    content: [
      {
        text: "Resumetra is an AI-powered resume analysis tool that provides:",
      },
      {
        text: "• Resume scoring across ATS compatibility, content quality, impact, and readability",
      },
      {
        text: "• Job match analysis comparing your resume against a job description",
      },
      {
        text: "• AI-powered resume tailoring suggestions for specific job descriptions",
      },
      {
        text: "• Career path mapping with personalized recommendations",
      },
      {
        text: "Guest users receive one free analysis without creating an account. Authenticated users (via Google Sign-In) receive unlimited access to all features including analysis history.",
      },
    ],
  },
  {
    title: "User Accounts",
    content: [
      {
        text: "Account creation is via Google OAuth. You are responsible for maintaining the security of your Google account. You must be at least 16 years old to use this service.",
      },
    ],
  },
  {
    title: "Acceptable Use",
    content: [
      {
        text: "You agree not to:",
      },
      {
        text: "• Use the service for any unlawful purpose",
      },
      {
        text: "• Submit content that is not your own resume without permission",
      },
      {
        text: "• Attempt to bypass usage limits or abuse the guest system",
      },
      {
        text: "• Use automated tools to access the service in ways that exceed normal use",
      },
      {
        text: "• Reverse engineer, decompile, or attempt to extract the underlying AI prompts or proprietary logic",
      },
    ],
  },
  {
    title: "AI-Generated Content",
    content: [
      {
        text: "Analysis results, feedback, suggestions, and tailored rewrites are generated by AI. They are provided for informational purposes only and do not constitute professional career advice, legal advice, or a guarantee of employment outcomes. You are responsible for reviewing and deciding whether to act on any AI-generated suggestions.",
      },
    ],
  },
  {
    title: "Intellectual Property",
    content: [
      {
        text: "Your resume content remains your intellectual property. We do not claim ownership of any content you submit for analysis. The Resumetra application, its design, and its underlying logic are the intellectual property of Resumetra.",
      },
    ],
  },
  {
    title: "Data and Privacy",
    content: [
      {
        text: "Our data practices are described in our Privacy Policy, which is incorporated into these Terms by reference. By using Resumetra, you also agree to the Privacy Policy.",
      },
    ],
  },
  {
    title: "Disclaimer of Warranties",
    content: [
      {
        text: 'Resumetra is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not guarantee that the service will be uninterrupted, error-free, or that analysis results will be accurate or complete.',
      },
    ],
  },
  {
    title: "Limitation of Liability",
    content: [
      {
        text: "To the fullest extent permitted by law, Resumetra and its creator shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service, including but not limited to decisions made based on AI-generated analysis results.",
      },
    ],
  },
  {
    title: "Modifications",
    content: [
      {
        text: "We may update these Terms from time to time. Continued use of the service after changes constitutes acceptance of the updated Terms. Changes will be reflected on this page with an updated effective date.",
      },
    ],
  },
  {
    title: "Termination",
    content: [
      {
        text: "We reserve the right to suspend or terminate access to the service at our discretion, with or without notice, for violation of these Terms or for any other reason.",
      },
    ],
  },
  {
    title: "Governing Law",
    content: [
      {
        text: "These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.",
      },
    ],
  },
  {
    title: "Contact",
    content: [
      {
        text: "For questions about these Terms, reach out via our GitHub page.",
      },
    ],
  },
];

const TermsOfService = () => (
  <div className="min-h-screen bg-white">
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-24">
      <Link
        to="/"
        className="text-amber-600 hover:text-amber-700 text-sm font-medium"
      >
        &larr; Back to Home
      </Link>

      <h1 className="mt-8 text-3xl md:text-4xl font-bold font-heading text-stone-900">
        Terms of Service
      </h1>
      <p className="mt-2 text-stone-400 text-sm">
        Effective date: April 26, 2026
      </p>

      <div className="mt-10 space-y-10">
        {sections.map((section) => (
          <section key={section.title}>
            <h2 className="text-xl font-semibold text-stone-900">
              {section.title}
            </h2>
            <div className="mt-3 space-y-3">
              {section.content.map((block, i) => (
                <p key={i} className="text-stone-500 leading-relaxed">
                  {block.text}
                </p>
              ))}
            </div>
          </section>
        ))}
      </div>
    </div>
  </div>
);

export default TermsOfService;
